swagger: '2.0'
info:
  description: |
    This is a prototype for a flask api
  version: 0.1.0
  title: flask microservice
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:5000
basePath: /

tags:
  - name: health
    description: API health check

schemes:
  - http

paths:
  /v1/health:
    get:
      tags:
        - health
      summary: Blueprint Health check
      operationId: v1getHealthCheck
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Health'
      security:
        - k8s_auth:
            - 'read:requests'
    post:
      tags:
        - health
      summary: Blueprint Health check
      operationId: v1postHealthCheck
      consumes:
        - application/json
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Health'
      security:
        - k8s_auth:
            - 'read:requests'
  /health:
    get:
      tags:
        - health
      summary: API Health check
      operationId: getHealthCheck
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Health'
      security:
        - k8s_auth:
            - 'read:requests'
    post:
      tags:
        - health
      summary: API Health check
      operationId: postHealthCheck
      consumes:
        - application/json
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Health'
      security:
        - k8s_auth:
            - 'read:requests'
securityDefinitions:
  k8s_auth:
    type: oauth2
    authorizationUrl: 'localhost:5000'
    flow: implicit
    scopes:
      'read:requests': get assignment
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Health:
    properties:
      timestamp:
        example: 1.548777376788353E9
        type: string
      version:
        example: "0.1.0"
        type: string
    type: object
